Cap gabbi to <2.9.0
Otherwise we get the error:
> ERROR: gabbi 2.9.0 has requirement urllib3<2.0.0,>=1.26.9, but you'll have urllib3 2.0.4 which is incompatible.

This requirement was introduced to gabbi in their commit cdab791:
https://github.com/cdent/gabbi/pull/322
This is between gabbi 2.8.0 and 2.9.0

Change-Id: I6fa4dbe08b270115620c7a9bee9b750b94fad1b8